language: go
go_import_path: gopkg.in/src-d/go-kallax.v1
sudo: required

matrix:
  allow_failures:
    - go: tip
  fast_finish: true
  include:
    - {os: linux,                    go: 1.9.x,  env: 'POSTGRESQL_VERSION=9.6'}
    - {os: linux,                    go: 1.10.x, env: 'POSTGRESQL_VERSION=9.4'}
    - {os: linux,                    go: 1.10.x, env: 'POSTGRESQL_VERSION=9.5'}
    - {os: linux,                    go: 1.10.x, env: 'POSTGRESQL_VERSION=9.6'}
    - {os: linux,                    go: tip,    env: 'POSTGRESQL_VERSION=9.6'}
    - {os: osx, osx_image: xcode9.3, go: 1.10.x, env: 'POSTGRESQL_VERSION=9.6'}

env:
  global:
    - DBNAME=kallax_test
    - DBUSER=postgres DBPASS=''
    - GOPATH=/tmp/whatever:$GOPATH

install:
  - wget -qO - https://raw.githubusercontent.com/smola/ci-tricks/master/get.sh | bash
  - go get -v -t ./...

before_script:
  - psql -c 'create database kallax_test;' -U postgres

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: change
    on_failure: always
